<h2><span class="mw-headline" id="Plot">Plot</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Distant_Lights_(2003_film)&amp;action=edit&amp;section=1" title="Edit section: Plot">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<p>Unlike many ensemble films, the subplots of the film mostly do not interconnect with each other, and the film ends without a finale. Instead, the story threads illustrate life on the border between two countries; what appears to be poverty and desperation to some is a promised land for others, worth risking their lives to reach. The threads are:
</p>
<ul><li>Kolya, a <a href="/wiki/Ukrainians" title="Ukrainians">Ukrainian</a>, has paid to be smuggled into Germany illegally; he finds he has been left on the Polish side of the border. When he is caught, a German interpreter agrees to smuggle him herself; he reaches <a href="/wiki/Berlin" title="Berlin">Berlin</a>.</li>
<li>Ingo, a German mattress salesman, finds business in Frankfurt to be minimal and the people self-interested. He is humiliated and becomes desperate, but may have found love in Simone.</li>
<li>Antoni, a Polish taxi driver, struggles to find the money to buy a <a href="/wiki/Mass_(liturgy)#Communion_rite" title="Mass (liturgy)">communion</a> dress for his daughter. By the time he is able to afford it, he is too late. (This subplot pays <a href="/wiki/Homage_(arts)" title="Homage (arts)">homage</a> to <a href="/wiki/Ken_Loach" title="Ken Loach">Ken Loach</a>'s film <i>Raining Stones</i> and <a href="/wiki/Mike_Leigh" title="Mike Leigh">Mike Leigh</a>'s <i><a href="/wiki/All_or_Nothing_(film)" title="All or Nothing (film)">All or Nothing</a></i>.)</li>
<li>Philip, a young German architect, runs into his Polish former girlfriend Beata while working on a building project in Słubice. Neither the romance nor the project works out.</li>
<li>Anna and Dimitri, a young Ukrainian couple, are swindled out of their money and try with Antoni's help to cross the river Oder, almost drowning in the attempt.</li>
<li>Andreas, a young German orphan who smuggles cigarettes, attempts to take the money and run away with a girl from the children's home.</li></ul>
