<h2><span class="mw-headline" id="Plot">Plot</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Heartbeat_(2011_film)&amp;action=edit&amp;section=1" title="Edit section: Plot">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<p>Yeon-hee (<a href="/wiki/Kim_Yunjin" class="mw-redirect" title="Kim Yunjin">Kim Yunjin</a>) is the principal of a prestigious English-teaching preschool in <a href="/wiki/Gangnam_(Seoul)" title="Gangnam (Seoul)">Gangnam</a>. She is a well-off widow, and a devout Christian. Yeon-hee remains hopeful in her faith that her daughter Ye-eun will be able to get a heart transplant surgery.
</p><p>But Yeon-hee has hired black-market organ dealers to search a healthy heart for her daughter. One donor is a live illegal immigrant, and Yeon-hee cannot bring herself to take his life in exchange for sending money to his family abroad. Time after time, the donors slip through her hands. Tired of waiting, Yeon-hee takes matters into her own hands, and betrays her conscience. She pays an exorbitant amount of money to arrange a transplant: the donor is a patient in a <a href="/wiki/Persistent_vegetative_state" title="Persistent vegetative state">persistent vegetative state</a>, and thus unable to consent.
</p><p>Yeon-hee rationalizes to her doctor friend that the vegetative patient is an answered prayer and pleads him to perform the transplant. Out of her guilt, Yeon-hee monologues to the patient, and cries that she would even go to hell for the illegal surgery, if it could save her little Ye-eun.
</p><p>When the time nears for her daughter's heart transplant surgery, Lee Hwi-do (<a href="/wiki/Park_Hae-il" title="Park Hae-il">Park Hae-il</a>), the son of the woman in the vegetative state, suddenly appears to stop the transplant. In the past, Hwi-do was a bad son often leeching money off of his mother. He parted ways with his mother, but when he learns of the current situation he tries to protect his mother. With only a single heart, Yeon-hee and Hwi-do are both desperate to save the one they love. Just when Yeon-hee is about to carry the patient in an ambulance, Hwi-do shows up and gets into the ambulance with them. During the ride, he confiscates the transplant contracts from Yeon-hee (signed by Kang, who dated Hwi-do's mother for money), and takes over the driver's seat. Yeon-hee runs after the ambulance, but it is gone.
</p><p>Hwi-do brings his mother to a hospital, but Yeon-hee tracks down the hospital. Hwi-do and his girlfriend visit Ye-eun's hospital room to take Ye-eun captive. Hwi-do decides that he won't abduct Ye-eun, until Yeon-hee calls him that she is sorry for taking his mother. He then kidnaps Ye-eun, of which Yeon-hee's doctor friend notifies Yeon-hee about.
</p><p>Ye-eun records a conversation on her teddy bear while telling Hwi-do that her mother is not a bad person. Hwi-do and his girlfriend form a friendship with Ye-eun. Still, Ye-eun uses the girlfriend's cellphone to text Yeon-hee the consonants of the location of Hwi-do's <a href="/wiki/Auto_repair_shop" class="mw-redirect" title="Auto repair shop">auto repair shop</a>.
</p><p>Yeon-hee receives the text, and discovers Hwi-do's place. She tazes Kang and offers Hwi-do an exchange of persons, which Hwi-do refuses. Hwi-do locks Ye-eun in his car and Yeon-hee keeps his mother in her van. Yeon-hee ambushes Hwi-do and beats him up with a plank from the street, while the organ dealers hired by Yeon-hee help carry Ye-eun to the van. Hwi-do and his girlfriend watch them drive off.
</p><p>Injured, Hwi-do limps to the hospital, to beat up Yeon-hee. Meanwhile, Yeon-hee rushes Ye-eun to the emergency room. Ye-eun tells her on the rolling cot, "Why did you hit someone like that? What if he died? I'm scared of you, Mom..."
Yeon-hee becomes weak in the knees and reflects. Hwi-do arrives and finds Yeon-hee sobbing and listening to the audio recorded by the teddy bear. Yeon-hee repents. She apologizes to Hwi-do and tells him that his mother would have done the same thing as she did, and that he should take his mother home.
</p><p>Hwi-do then finds his mother, and asks her to move her hand. But her heartbeat fails. Yeon-hee weeps with him, and Hwi-do tells Yeon-hee that his mother wishes the transplant to happen.
</p><p>Months later, during <a href="/wiki/Christmas_Eve" title="Christmas Eve">Christmas Eve</a>, Yeon-hee and a healthy Ye-eun are in a car on the way to a restaurant. Ye-eun says that the car seems weird, and needs to be checked out. They arrive at Hwi-do's auto shop, where Ye-eun gives her teddy bear as a present to Hwi-do's now-pregnant girlfriend. Hwi-do invites Yeon-hee for dinner. Yeon-hee quietly goes into the back of the shop and smiles at the picture of Hwi-do's mother.
</p>
