<h2><span class="mw-headline" id="Plot">Plot</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Sabotage_(2014_film)&amp;action=edit&amp;section=1" title="Edit section: Plot">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<p>John "Breacher" Wharton is the leader of the <a href="/wiki/Drug_Enforcement_Administration" title="Drug Enforcement Administration">Drug Enforcement Administration</a>'s Special Operations Team, which consists of James "Monster" Murray, Monster's wife Lizzy Murray, Joe "Grinder" Philips, Julius "Sugar" Edmonds, Eddie "Neck" Jordan, Tom "Pyro" Roberts, Bryce "Tripod" McNeely and "Smoke" Jennings.
</p><p>During a raid on a cartel warehouse, Smoke is killed, the team steals $10 million and hides it in the sewer while blowing up the rest to cover their tracks. The money disappears, and their superior Floyd Demel suspends them while the DEA investigates the team for the theft. After several months without any confessions or evidence of their participation, the team is reinstated.
</p><p>Pyro is killed after an unidentified stranger tows his trailer onto a railroad crossing while he is unconscious and is rammed by a train before he can escape. <a href="/wiki/Atlanta_Police_Department" title="Atlanta Police Department">Atlanta Police</a> homicide detective Caroline Brentwood and her partner Darius Jackson are assigned to the case and interrogate Pyro's teammates.
</p><p>Brentwood notes Neck is aggressively avoiding interrogation, and Breacher accompanies her to Neck's house, hopeful he will cooperate. When they arrive, they find him nailed to the ceiling and disemboweled. Brentwood recognizes the execution as the <i><a href="/wiki/Modus_operandi" title="Modus operandi">modus operandi</a></i> of the cartels, leading Breacher to assume the cartel is hunting the team over the stolen money.
</p><p>Breacher and Brentwood visit Tripod, who left the DEA after being suspended, and find him dead after a shootout in which he killed an assailant Breacher identified as a cartel enforcer. Monster later visits Brentwood, who is suspicious of Breacher. Monster tells her that Breacher's family was kidnapped by the cartels, who videotaped their murders and later sent the tape to Breacher along with the severed body parts of his wife and son. Breacher spent months searching for his family's killers before the team convinced him to move on. Brentwood apologizes to Breacher, and they have sex.
</p><p>Jackson traces the dead enforcer's cellphone to a cartel <a href="/wiki/Safe_house" title="Safe house">safe house</a>, which is raided by Breacher and his team, but the enforcers are not there. They are later found dead at the bottom of a river near Tripod's house, and Detective Brentwood realizes that they were killed before Pyro and Neck, meaning someone is framing the cartel for killing their team members.
</p><p>Breacher reunites the team to tell them what happened, and Lizzy lashes out and reveals she's been having an affair with Sugar. Grinder confides in Brentwood that they stole the money. Breacher and Brentwood meet with Grinder in a local restaurant and Lizzy kills Grinder using a sniper rifle. Lizzy and Sugar have been behind the murders of their teammates. Lizzy is putting together her gear to leave the country with Sugar when Monster figures out she's behind the murders. He destroys Lizzy's passport to prevent her from leaving the country, and Lizzy attacks him with a knife, killing him.
</p><p>Breacher and Brentwood go to Lizzy's house and find Monster's body stuffed in a refrigerator. Lizzy calls Breacher, pretending to be alone, and arranges a meeting at a parking garage. Breacher goes there with Detective Brentwood, who ducks down in the car, unseen. Lizzy and Sugar ambush Breacher, and Brentwood assists Breacher. Lizzy and Sugar drive away, pursued by Breacher and Brentwood. After a lengthy chase, Sugar and Lizzy's car crashes into a tow truck, the ramp decapitating Sugar.
</p><p>Breacher and Brentwood confront a dying Lizzy, who accuses the team of stealing the money behind her back, motivating her to seek revenge. Brentwood is puzzled, assuming Lizzy had stolen the money. Breacher tells the dying Lizzy that he took the money. Lizzy tries to reach for her weapon and Breacher kills her. The local cops arrive and Breacher disappears.
</p><p>Weeks later, Breacher is in Mexico, where he uses the stolen money to bribe a corrupt police official into helping him identify Brujo, the man who murdered his family. Breacher finds him in a Mexican bar and kills him and others loyal to him in a shootout and he is shot in the chest. Breacher sits at a table, takes a shot of whiskey, lights up one last cigar and smiles as he hears the sirens.
</p>
