<h2><span class="mw-headline" id="Plot">Plot</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=Deathdream&amp;action=edit&amp;section=1" title="Edit section: Plot">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<p>In <a href="/wiki/Vietnam_war" class="mw-redirect" title="Vietnam war">Vietnam</a>, American soldier Andy Brooks is shot by a sniper and falls to the ground. As he dies, he hears his mother's voice calling out, "Andy, you'll come back. You've got to. You promised." The voice becomes sinister and muffled as Andy's eyes close. Sometime later, his family receives notice of his death in combat.
</p><p>Back home, Andy's father, Charles, and sister, Cathy, begin to grieve, but his mother, Christine, becomes irate and refuses to believe that Andy has died. Hours later, in the middle of the night, Andy arrives at the front door in full uniform and apparently unharmed; the family accepts the notice of his death as a clerical error and welcomes him back with joy.
</p><p>Over the next few days, Andy displays strange, withdrawn behavior, speaking only rarely, dressing in an unusually concealing manner, and spending his days sitting around the house listless and anemic. Meanwhile, local police investigate the murder of a local trucker, who was found with his throat slashed and his body drained of blood after telling diner patrons that he'd picked up a hitchhiking soldier.
</p><p>Charles attempts to confront Christine about Andy's erratic behavior, which causes tension between the couple. Christine insists that Charles was too withdrawn and authoritarian toward Andy; Charles counters that Christine made Andy too sensitive by smothering him. Andy continues to display unusual behavior: he attacks a neighbor boy who attempts to demonstrate his karate skills, then kills the family dog when it tries to protect the child. At night, Andy becomes inexplicably lively and animated, wandering the town and spending time in the local cemetery.
</p><p>Charles brings home a doctor and family friend, who offers Andy a checkup. He later tells Charles about the truck driver and says he needs to inform the police about the suspicious coincidence of Andy's return. Andy visits him in the middle of the night demanding a checkup, but the doctor can't detect a pulse or heartbeat. Andy tells him, "I died for you, Doc. Why shouldn't you return the favor?" He attacks and kills the doctor, then uses a syringe to inject the doctor's blood into his arm. It's clear that Andy is some kind of <a href="/wiki/Vampire" title="Vampire">vampire</a> or <a href="/wiki/Zombie" title="Zombie">zombie</a> who needs the blood of others to reinvigorate his decaying body.
</p><p>The next day, Charles becomes convinced his son is responsible for the deaths. When Christine tells him that Andy is on a double date with his high school sweetheart, Joanne, his sister and his best friend, Charles gets his gun and goes looking for them. At a drive-in cinema, Andy visibly decays due to lack of blood. He attacks and kills Joanne and his friend. The other patrons witness the attack. Andy flees before he can inject his victims' blood, running over and killing one of the patrons.
</p><p>Andy returns home, where his mother protects him from his father. Charles commits suicide when he sees what his son has become. As Christine is driving Andy away, he is shot at by police. They pursue him, and the chase ends at the graveyard where he had been spending his free time. They discover Andy's decayed corpse writhing in a shallow grave beneath a tombstone on which Andy himself had scrawled his own name and the dates of his birth and death. Christine sobs as she tries to cover the corpse with dirt.
</p>
