<h2><span class="mw-headline" id="Plot">Plot</span></h2>
<p>The film opens as two <a href="/wiki/White_nationalists" class="mw-redirect" title="White nationalists">white nationalists</a> destroy an apartment complex in which most of the residents are <a href="/wiki/Minorities" class="mw-redirect" title="Minorities">minorities</a>. Veteran <a href="/wiki/Police_officer" title="Police officer">police officer</a>, Sgt. Lou Swanson, and his <a href="/wiki/Police_dog" title="Police dog">police dog</a>, Reno, investigate the crime and realize the explosives are military in style. Their investigation takes them to the harbor, where they find a ship loaded with weapons. They are discovered and shot. Lou dies, but Reno survives.
</p><p>Maverick cop Jake Wilder (Chuck Norris), is called by police captain Ken Callahan (<a href="/wiki/Clyde_Kusatsu" title="Clyde Kusatsu">Clyde Kusatsu</a>), who requests Jake to take over the case. Jake is angered that he has to work with Reno, despite Reno proving himself capable through a battle training scenario.
</p><p>Meanwhile, <a href="/wiki/Neo-Nazis" class="mw-redirect" title="Neo-Nazis">Neo-Nazis</a> are trying to smuggle weapons across the border from Mexico. It is implied that they murdered their <a href="/wiki/Mexico" title="Mexico">Mexican</a> <a href="/wiki/Arms_trafficking" title="Arms trafficking">arms dealers</a>. They are stopped by the <a href="/wiki/United_States_Border_Patrol" title="United States Border Patrol">Border Patrol</a> and try to escape, but their car is destroyed in the process.
</p><p>Jake and Reno survive an assassination attempt at Jake's home. Afterwards, Jake is visiting his mother, who reveals that Adolf Hitler's birthday will be the following day. Jake realizes this a clue, and takes off running. The police department works with the sheriff's office, as well as the FBI in determining where the Neo-Nazis are going to hit. One officer reveals that on Hitler's birthday (April 20), the <a href="/wiki/Pope" title="Pope">Pope</a>, and several other of his esteemed <a href="/wiki/Bishops" class="mw-redirect" title="Bishops">bishops</a> will host the Coalition for Racial Unity.
</p><p>As the Neo-Nazis hitmen are practicing for their attack, the leaders are revealed not to be just one white supremacist group, but an alliance of several including the <a href="/wiki/Ku_Klux_Klan" title="Ku Klux Klan">Ku Klux Klan</a>, the <a href="/wiki/Aryan_Nations" title="Aryan Nations">Aryan Nations</a>, and the <a href="/wiki/Creativity_(religion)" title="Creativity (religion)">Church of the Creator</a>. They plan to use their attack on the Coalition for Racial Unity as an opportunity to unite all the Neo-Nazi groups in the US, as well as the world.
</p><p>Jake discovers the location of the warehouse where the Neo-Nazis are located. He and Reno go undercover and manage to steal a piece of evidence that could be used to convict the Neo-Nazi leaders. They are discovered and Jake orders Reno to flee with the evidence. Wilder subdues several radicals during the following fight, however he is finally captured, after a dozen attackers confront him at all once, and he's then hit on the head with a blunt object. He wakes up to find that he is tied up and the Neo-Nazi plan is now under way. Reno finds Jake, and eats away his rope bindings, just before a Neo-Nazi has the chance to kill him. Jake is able to call the police chief and tells him that the plan is in motion.
</p><p>The police, FBI, CTU, and Sheriff's Department arrive as the Coalition for Racial Unity is attacked and in a gun battle many Neo-Nazis are killed. The Pope and his Bishops get in their bulletproof car, but it is rigged to explode. Wilder defuses the bomb, while Reno goes after the Neo-Nazi leader. Wilder chases after him as well, and after a vicious fight, manages to subdue him. Reno is set to attack the Neo-Nazi leader, who confesses to killing Reno's former veteran cop owner. Just before Reno can attack the leader, Lou's grandson, Matthew, arrives to stop him.
</p>
