<h2><span class="mw-headline" id="Plot">Plot</span><span class="mw-editsection"><span class="mw-editsection-bracket">[</span><a href="/w/index.php?title=W.E.&amp;action=edit&amp;section=1" title="Edit section: Plot">edit</a><span class="mw-editsection-bracket">]</span></span></h2>
<p>Wally Winthrop is a lonely housewife, living in 1998 in New York City. She is neglected by her psychiatrist husband, William Winthrop and finds solace in the love story of <a href="/wiki/Edward_VIII" title="Edward VIII">King Edward VIII</a> and his lover, <a href="/wiki/Wallis_Simpson" title="Wallis Simpson">Wallis Simpson</a>. Wally travels to the <a href="/wiki/Sotheby%27s" title="Sotheby&#39;s">Sotheby's</a> auction of the Windsor Estate, showcasing items used by Wallis and Edward in their lifetime, and reminisces about their relationship.
</p><p>In 1930, Edward throws a party at his new home in <a href="/wiki/Fort_Belvedere,_Berkshire" class="mw-redirect" title="Fort Belvedere, Berkshire">Fort Belvedere</a>, in <a href="/wiki/Windsor_Great_Park" title="Windsor Great Park">Windsor Great Park</a> where he meets Wallis through his mistress, <a href="/wiki/Thelma_Furness,_Viscountess_Furness" title="Thelma Furness, Viscountess Furness">Lady Furness</a>. The two develop a mutual attraction, despite Wallis being married to <a href="/wiki/Ernest_Simpson" title="Ernest Simpson">Ernest Simpson</a>, and become lovers while Lady Furness is abroad. Back at Sotheby's, Wally is interrupted by a guard named Evgeni, who takes a liking to her.
</p><p>Edward and Wallis continue their love affair while touring throughout Europe, where he gives her a number of jewels and assumes the initials W.E. By the end of 1934, Edward is irretrievably besotted with Wallis. He decides to introduce Wallis to his parents, <a href="/wiki/King_George_V" class="mw-redirect" title="King George V">King George V</a> and <a href="/wiki/Mary_of_Teck" title="Mary of Teck">Queen Mary</a>, but she is portrayed in a bad light by Edward's sister-in-law <a href="/wiki/Queen_Elizabeth_The_Queen_Mother" title="Queen Elizabeth The Queen Mother">Elizabeth</a>. A distraught Wallis wants to end the relationship but Edward pacifies her.
</p><p>In modern day New York, Wally's husband William refuses to try to conceive a child with her and she subsequently starts <a href="/wiki/In_vitro_fertilisation" title="In vitro fertilisation">In vitro fertilisation</a>. Wally gradually becomes attracted to Evgeni and eventually goes on a date with him. She asks Evgeni more about Edward and Wallis's story, while pondering on her relationship with William. After attending an auction at Sotheby's, where she spends ten thousand dollars, Wally returns home to a drunken, confrontational William. He beats Wally, leaving her badly injured on the floor.
</p><p>The <a href="/wiki/National_Government_(United_Kingdom)" title="National Government (United Kingdom)">National Government</a> refuses to recognise the relationship of Edward and Wallis because she is a divorcée. On the night of 11 December 1936, Edward broadcasts to the nation and the <a href="/wiki/British_Empire" title="British Empire">British Empire</a> explaining his decision to <a href="/wiki/Edward_VIII_abdication_crisis" title="Edward VIII abdication crisis">abdicate</a> the throne in favour of his brother <a href="/wiki/George_VI" title="George VI">Bertie</a>. He says, "I have found it impossible to carry the heavy burden of responsibility and to discharge my duties as King, as I would wish to do, without the help and support of the woman I love." Wallis, who has fled to Villa Lou Viei, near <a href="/wiki/Cannes" title="Cannes">Cannes</a>, hears of this and has no choice other than to join Edward.
</p><p>Back in New York, Evgeni has been trying to phone Wally, who lays unconscious. He runs to her apartment to check on her, finding her injured on the floor. He takes her back to his home in Brooklyn. As she recovers, Wally finds a new hope and direction in life. She falls in love with Evgeni, divorces William and moves on.
</p><p>Reading a series of letters, kept in millionaire <a href="/wiki/Mohamed_Al-Fayed" title="Mohamed Al-Fayed">Mohamed Al-Fayed</a>'s collection, Wally realises that Wallis was stuck in a relationship with Edward for the rest of her life. An imaginary monologue with Wallis shows the two women discussing the similarity of their lives, but in the end only Wally has found happiness. She leaves behind her fascination with Wallis and Edward's relationship and learns from her doctor that she is pregnant.
</p>
